version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: scentdna_postgres
    environment:
      POSTGRES_USER: scentdna_user
      POSTGRES_PASSWORD: scentdna_password
      POSTGRES_DB: scentdna_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: